### ISSUE TITLE
Baysian: list indices must be integer

### ISSUE THREAD

**Issue by hyunjimoon** [I2MAX-LearningProject/Flask-server#8]
## Problem File Name
LearningManager.py
## Expected behavior
work well
## Actual behavior
does not work well
## Steps to reproduce the behavior
It always happen.

Run server program(index.py)
Upload test data (Use post man /upload/)

## Program printed log
```
C:\Users\User\Anaconda3\envs\TensorFlow35\python.exe C:/Users/User/Documents/GitHub/Flask-server/index.py
INFO:root: 09:52:58 [FirebaseDatabaseManager] <GetFirebaseConnection> (getting firebase connection)
INFO:root: 09:52:58 [FirebaseDatabaseManager] <GetFirebaseConnection> (connection successful)
INFO:werkzeug: * Restarting with stat
INFO:root: 09:52:59 [FirebaseDatabaseManager] <GetFirebaseConnection> (getting firebase connection)
INFO:root: 09:52:59 [FirebaseDatabaseManager] <GetFirebaseConnection> (connection successful)
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 308-191-063
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:root: 09:55:38 [RouteManager] <UploadRawDatas> (json data: {'Date': ['2017-08-11', '2017-08-12', '2017-08-13', '2017-08-14', '2017-08-15'], 'Data': [20.0, 30.0, 401.0, 50.0, 60.0], 'Day': 4})
INFO:root: 09:55:38 [BackgroundProcessManager] <UploadRawDatas> (data: [20.0, 30.0, 401.0, 50.0, 60.0], date: ['2017-08-11', '2017-08-12', '2017-08-13', '2017-08-14', '2017-08-15'], day 4)
INFO:root: 09:55:39 [FirebaseDatabaseManager] <GetLastProcessId> (last process id: 63)
INFO:root: 09:55:40 [FirebaseDatabaseManager] <CreateNewProcessTable> (creating new table)
INFO:root: 09:55:41 [FirebaseDatabaseManager] <StoreInputData> (saved data)
INFO:root: 09:55:41 [FirebaseDatabaseManager] <UpdateLastProcessId> (last process id updated: 64)
INFO:root: 09:55:41 [LearningManager] <LearningModuleRunner> (start of learning #64)
INFO:werkzeug:127.0.0.1 - - [18/Aug/2017 09:55:41] "POST /upload/ HTTP/1.1" 200 -
INFO:root: 09:55:41 [LearningManager] <LearningModuleRunner> (start)
INFO:root: 09:55:41 [LearningManager] <LearningModuleRunner> (LSTMpreprocessing succeed)
INFO:root: 09:55:41 [LearningManager] <LearningModuleRunner> (LSTMpredict succeed)
INFO:root: 09:55:41 [LearningManager] <LearningModuleRunner> (LSTMevaluation succeed)
INFO:root: 09:55:41 [LearningManager] <LearningModuleRunner> (BAYSEIANpreprocessing dsY to list succeed)
INFO:root: 09:55:41 [LearningManager] <LearningModuleRunner> (BAYSEIANdataFrame succeed)
INFO:root: 09:55:41 [LearningManager] <LearningModuleRunner> (BAYSEIANpreprocessing succeed)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\TensorFlow35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\User\Anaconda3\envs\TensorFlow35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Documents\GitHub\Flask-server\Core\LearningManager.py", line 59, in LearningModuleRunner
    mockForecast['Bayseian'] = Bayseian(preprocessedData=trainXY, forecastDay=testSize)[0]
  File "C:\Users\User\Documents\GitHub\Flask-server\Core\LearningManager.py", line 137, in Bayseian
    model.fit(preprocessedData)
  File "C:\Users\User\Anaconda3\envs\TensorFlow35\lib\site-packages\fbprophet\forecaster.py", line 483, in fit
    history = df[df['y'].notnull()].copy()
TypeError: list indices must be integers or slices, not str


```

**Comment by hyunjimoon** [comment]
solved error by designing algorithm in a different manner.
In my opinion the original error was due to trainXY form.

resolved error with the following code.
    mockDs = rawArrayDatas[0][:trainSize]
    mockY = list(np.log(rawArrayDatas[1][:trainSize]))
    mockSales = list(zip(mockDs, mockY))


```
C:\Users\lg\Anaconda3\envs\tensorflow\python.exe C:/Users/lg/Documents/GitHub/Flask-server/index.py
INFO:root: 22:08:03 [FirebaseDatabaseManager] <GetFirebaseConnection> (getting firebase connection)
INFO:root: 22:08:03 [FirebaseDatabaseManager] <GetFirebaseConnection> (connection successful)
INFO:werkzeug: * Restarting with stat
INFO:root: 22:08:05 [FirebaseDatabaseManager] <GetFirebaseConnection> (getting firebase connection)
INFO:root: 22:08:05 [FirebaseDatabaseManager] <GetFirebaseConnection> (connection successful)
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 295-188-263
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:root: 22:08:07 [RouteManager] <UploadRawDatas> (json data: {'Day': 2, 'Data': [1414.0, 1414.0, 4321.0, 3333.0, 3000.0, 6000.0], 'Date': ['2017-08-15', '2017-08-16', '2017-08-17', '2017-08-18', '2017-08-19', '2017-08-20']})
INFO:root: 22:08:07 [BackgroundProcessManager] <UploadRawDatas> (data: [1414.0, 1414.0, 4321.0, 3333.0, 3000.0, 6000.0], date: ['2017-08-15', '2017-08-16', '2017-08-17', '2017-08-18', '2017-08-19', '2017-08-20'], day 2)
INFO:root: 22:08:09 [FirebaseDatabaseManager] <GetLastProcessId> (last process id: 80)
INFO:root: 22:08:10 [FirebaseDatabaseManager] <CreateNewProcessTable> (creating new table)
INFO:root: 22:08:10 [FirebaseDatabaseManager] <StoreInputData> (saved data)
INFO:root: 22:08:11 [FirebaseDatabaseManager] <UpdateLastProcessId> (last process id updated: 81)
INFO:root: 22:08:11 [LearningManager] <LearningModuleRunner> (start of learning #81)
INFO:root: 22:08:11 [LearningManager] <LearningModuleRunner> (traindata create success)
INFO:root: 22:08:11 [LearningManager] <LearningModuleRunner> (realdata create success)
INFO:werkzeug:127.0.0.1 - - [18/Aug/2017 22:08:11] "POST /upload/ HTTP/1.1" 200 -
Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
STAN OPTIMIZATION COMMAND (LBFGS)
init = user
save_iterations = 1
init_alpha = 0.001
tol_obj = 1e-12
tol_grad = 1e-08
tol_param = 1e-08
tol_rel_obj = 10000
tol_rel_grad = 1e+07
history_size = 5
seed = 173218961
initial log joint probability = -2.01793
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
      14       11.3827   0.000364685       77.0412   3.702e-06       0.001       68  LS failed, Hessian reset 
      17       11.3941   1.84334e-06       58.9861   2.412e-08       0.001      119  LS failed, Hessian reset 
      20        11.395   2.77505e-06         76.34   4.707e-08       0.001      171  LS failed, Hessian reset 
      23       11.3957   1.76501e-06       58.9306   2.314e-08       0.001      217  LS failed, Hessian reset 
      26       11.3965   6.73804e-06       76.1952   1.144e-07       0.001      268  LS failed, Hessian reset 
      29       11.3979   3.39773e-06       58.8578   4.466e-08       0.001      315  LS failed, Hessian reset 
      35       11.3983   6.03032e-08       58.8489    7.93e-10       0.001      368  LS failed, Hessian reset 
      37       11.3983   4.75903e-09       76.0482   4.844e-11       0.001      413  LS failed, Hessian reset 
Optimization terminated normally: 
  Convergence detected: absolute parameter change was below tolerance
INFO:root: 22:08:12 [LearningManager] <LearningModuleRunner> (mockforecast success)
Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
STAN OPTIMIZATION COMMAND (LBFGS)
init = user
save_iterations = 1
init_alpha = 0.001
tol_obj = 1e-12
tol_grad = 1e-08
tol_param = 1e-08
tol_rel_obj = 10000
tol_rel_grad = 1e+07
history_size = 5
seed = 976074051
initial log joint probability = -2.01801
    Iter      log prob        ||dx||      ||grad||       alpha      alpha0  # evals  Notes 
      47       17.2078   6.19208e-09       98.1708      0.1955           1      100   
Optimization terminated normally: 
  Convergence detected: absolute parameter change was below tolerance
INFO:root: 22:08:13 [LearningManager] <LearningModuleRunner> (realforecast success)
INFO:root: 22:08:14 [FirebaseDatabaseManager] <StoreOutputData> (saved data)
```
